# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\_files\VSCode\TIK\lab2\EntropyComparer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit

from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtCore import QRegExp

import math;
import numpy as np
import entropy as ntrp

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 121)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)

        class DigitDotSemicolonInput(QLineEdit):
            def __init__(self, parent=None):
                super().__init__(parent)
                regex = QRegExp(r"[0-9.;]*")
                validator = QRegExpValidator(regex, self)
                self.setValidator(validator)

        self.lineEdit_insert_A = DigitDotSemicolonInput(Dialog)
        self.lineEdit_insert_A.setEnabled(True)
        self.lineEdit_insert_A.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.lineEdit_insert_A.setObjectName("lineEdit_insert_A")

        self.label_insert_A = QtWidgets.QLabel(Dialog)
        self.label_insert_A.setGeometry(QtCore.QRect(40, 10, 171, 20))
        self.label_insert_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_insert_A.setObjectName("label_insert_A")

        self.label_Insert_B = QtWidgets.QLabel(Dialog)
        self.label_Insert_B.setGeometry(QtCore.QRect(40, 60, 171, 20))
        self.label_Insert_B.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Insert_B.setObjectName("label_Insert_B")

        self.lineEdit_Insert_B = DigitDotSemicolonInput(Dialog)
        self.lineEdit_Insert_B.setEnabled(True)
        self.lineEdit_Insert_B.setGeometry(QtCore.QRect(70, 80, 113, 20))
        self.lineEdit_Insert_B.setObjectName("lineEdit_Insert_B")

        self.pushButton_compare = QtWidgets.QPushButton(Dialog)
        self.pushButton_compare.setGeometry(QtCore.QRect(270, 50, 75, 23))
        self.pushButton_compare.setObjectName("pushButton_compare")
        self.pushButton_compare.clicked.connect(self.compare)

        self.label_tag_A = QtWidgets.QLabel(Dialog)
        self.label_tag_A.setGeometry(QtCore.QRect(190, 30, 47, 13))
        self.label_tag_A.setObjectName("label_tag_A")
        self.label_tag_A.setVisible(False)

        self.label_tag_B = QtWidgets.QLabel(Dialog)
        self.label_tag_B.setGeometry(QtCore.QRect(190, 80, 47, 13))
        self.label_tag_B.setObjectName("label_tag_B")
        self.label_tag_B.setVisible(False)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Порівнювач ентропій"))
        self.label_insert_A.setText(_translate("Dialog", "Розподіли імовірностей A"))
        self.label_Insert_B.setText(_translate("Dialog", "Розподіли імовірностей B"))
        self.pushButton_compare.setText(_translate("Dialog", "Порівняти"))
        self.label_tag_A.setText(_translate("Dialog", "<"))
        self.label_tag_B.setText(_translate("Dialog", "<"))
    
    def compare(self):
        a_input_str = self.lineEdit_insert_A.text()
        a_input_arr = np.array(a_input_str.split(";")).astype(float)

        b_input_str = self.lineEdit_Insert_B.text()
        b_input_arr = np.array(b_input_str.split(";")).astype(float)

        a_entropy = ntrp.unconditional_entropy_from_array(a_input_arr)
        b_entropy = ntrp.unconditional_entropy_from_array(b_input_arr)
        
        self.label_tag_A.setVisible(a_entropy > b_entropy)
        self.label_tag_B.setVisible(a_entropy < b_entropy)

        print(f"Entropy of A: {a_entropy}")
        print(f"Entropy of B: {b_entropy}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
